### PR TITLE
jCardSim port to Android

### PR DESCRIPTION
**Pull request by frankmorgner**
I created a simple [Host Card Emulation (HCE) App for Android](https://frankmorgner.github.io/vsmartcard/ACardEmulator/README.html) which integrates jCardSim to emulate some open source java card applets. Porting jCardSim was rather straight forward:

1. remove all RMI components which Android's JVM does not support
2. replace bouncycastle with spongycastle
3. duplicate the standard javax/smartcardio/*
4. exclude APDUScriptTool.java from compilation (this is done in the build script of my App)

I guess there is a better (i.e. non intrusive) method of working around the problems which propably involve some build configuration magic, what do you think?

Please note, that this is more like a request for comments than an actual pull request...

### CODE REVIEW

**Comment by licel** [comment]
Thank you for the great work. We will make the maven build script suitable to generate Android version of jCardSim soon.

**Comment by marll** [comment]
In file  AndroidManifest is used
uses-feature android: name = "android.hardware.nfc"
instead of
uses-feature android: name = "android.hardware.nfc.hce"
Why?
Thanks

**Comment by frankmorgner** [comment]
@marl this looks like an error on my side.

**Comment by robertbachmann** [comment]
Hi @frankmorgner,

I've addressed the problems with *bouncycastle* and *java.rmi* in commit 2bcdc835fa5b0843fd2f73b1698f41950d25bccf.

Regarding *javax.smartcardio*, you can avoid that dependency by replacing `CardSimulator` with `Simulator`. The latter intentionally does not depend on *javax.smartcardio*:

````diff
diff --git a/ACardEmulator/app/src/main/java/com/vsmartcard/acardemulator/SimulatorService.java b/ACardEmulator/app/src/main/java/com/vsmartcard/acardemulator/SimulatorService.java
index e70954a..10170ed 100644
--- a/ACardEmulator/app/src/main/java/com/vsmartcard/acardemulator/SimulatorService.java
+++ b/ACardEmulator/app/src/main/java/com/vsmartcard/acardemulator/SimulatorService.java
@@ -30,7 +30,8 @@ import android.support.v4.content.LocalBroadcastManager;
 import android.util.Log;
 
 import com.licel.jcardsim.samples.HelloWorldApplet;
-import com.licel.jcardsim.smartcardio.CardSimulator;
+import com.licel.jcardsim.base.Simulator;
+import com.licel.jcardsim.base.SimulatorRuntime;
 import com.licel.jcardsim.utils.AIDUtil;
 
 import net.pwendland.javacard.pki.isoapplet.IsoApplet;
@@ -62,11 +63,11 @@ public class SimulatorService extends HostApduService {
     public static final String EXTRA_DESELECT = "MSG_DESELECT";
     public static final String EXTRA_INSTALL = "MSG_INSTALL";
 
-    private static CardSimulator simulator = null;
+    private static Simulator simulator = null;
 
     private void createSimulator() {
         String aid, name, extra_install = "", extra_error = "";
-        simulator = new CardSimulator();
+        simulator = new Simulator(new SimulatorRuntime());
 
         name = getResources().getString(R.string.applet_helloworld);
         aid = getResources().getString(R.string.aid_helloworld);
````

**Comment by frankmorgner** [comment]
@robertbachmann do you know how I would have to integrate jCardSim (Maven) into the grade build of my Android App?

I could download the jar from a maven repository (https://docs.gradle.org/current/userguide/artifact_dependencies_tutorial.html) but the android version is not published as far as I know.

The other thing I could try to do is rewrite my grade build script so that it contains the essence of your pom.xml modifications. That, however, seems redundant to me (and it is not future proof either).

**Comment by robertbachmann** [comment]
@frankmorgner, you could try the following steps (untested): 

1) Change the path in your .gitmodules to https://github.com/licel/jcardsim
2) Add the ``mavenLocal`` repository to your gradle script.
````
repositories {
  mavenLocal()
}
````
3) Use gradle's *Exec* task to run "mvn clean install" in the jcardsim directory.
4) Import jcardsim as a gradle dependency

**Comment by frankmorgner** [comment]
thanks @robertbachmann the android build works as expected.

I ended compiling it by hand and included the android library only https://github.com/frankmorgner/vsmartcard/commit/b91da672817bf6fa8f297d67f5b77478af77da53

**Pull request closed without merging**
